APP:
  NAME: pharmaniaga-mpi
  ENV: staging
  URL: https://mpi-stagingv2.olin.co.id
  PORT: 8010
  KEY: A9NaQU1yq3h!Rl9yQj&6w^P911lFHZU#

ROUTE:
  METHODS: [GET, POST, PUT, DELETE]
  HEADERS: [Content-Type, Authorization, Authorization-ID, Accept-Key]
  ORIGIN: ['*']

DATABASE:
  READ:
    USERNAME: mpi01
    PASSWORD: MP1Ol1n01
    URL: sqlserver.olin.co.id
    PORT: 1433
    DB_NAME: master
    MAXIDLECONNS: 5
    MAXOPENCONNS: 5
    MAXLIFETIME: 31
    TIMEOUT: 2
    SSL_MODE: require
  WRITE:
    USERNAME: mpi01
    PASSWORD: MP1Ol1n01
    URL: sqlserver.olin.co.id
    PORT: 1433
    DB_NAME: master
    MAXIDLECONNS: 5
    MAXOPENCONNS: 5
    MAXLIFETIME: 31
    TIMEOUT: 2
    SSL_MODE: require

AUTHORIZATION:
  JWT:
    IS_ACTIVE: true
    ACCESS_TOKEN_SECRET_KEY: 11JGC$K7VL6TOvt!
    ACCESS_TOKEN_DURATION: 30
    REFRESH_TOKEN_SECRET_KEY: G3zl^2XC0PnU62mk
    REFRESH_TOKEN_DURATION: 365
  PUBLIC:
    SECRET_KEY: d5Bz#@1bXvgk4C0o

KEY:
  USER: 5EP45lgo!D6skeWADPW9ssLNcCJ$woLk
